### ISSUE TITLE
how about offering a rude and robust module to generate large polymer (DP>1000) ?

### ISSUE THREAD

**Issue by smzxjqxz** [polysimtools/pysimm#16]
The random_walk module is great, but when building a polymer composed of over 1000 monomer, it is getting slower and slower. If there is another rude approach with constant last_backbone_vector, so I can chose the random or rude way as I need, that would be great :)

However, simply repeat the random_walk process already helps me out, thank you!

**Comment by mefortunato** [comment]
Thanks for raising an issue. For building large polymer chains, you should try to utilize multiple processors. This can be achieved by using the settings keyword argument, which accepts a dictionary of simulation settings for the MD used during the random_walk algorithm. With each insertion of a new monomer, the number of particles increases, consequently increasing the computational cost. You can offset this by increasing the number of processors being used for each MD simulation.

Please try the following code:

`random_walk(<mon>, 1000, forcefield=<forecfield>, settings={'np': <num_proc>})`

You should notice a decrease in the time-to-solution and upon checking the log file, you should notice the LAMMPS simulations is using multiple processors.
