### ISSUE TITLE
lmps.quick_min ()  error

### ISSUE THREAD

**Issue by yerdna14** [polysimtools/pysimm#25]
hi, i was able to install pysimm but in the methanol example in the lmps.quick_min () part I get an error this PysimmError: A pair_style must be defined during initialization, could it help me

**Comment by AlleksD** [comment]
Hi, thanks for the comment!

as for now, I cannot reproduce the bug:
That is what I have for Python 2.7.14:

```Python
Python 2.7.14 (default, Feb 27 2018, 12:31:17)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pysimm import system, lmps, forcefield
>>> s = system.read_pubchem_smiles('CO')
making request to pubchem RESTful API:
https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/CO/SDF/?record_type=3d
(debug) PySIMM: reading string
>>> len(s.particles)
6
>>> s.apply_forcefield(forcefield.Dreiding())
>>> s.pair_style
'lj'

```

Is there something you have added to the script?
Can you please send us the full std output of the script


Alex

**Comment by yerdna14** [comment]
thanks, it was a problem with the example 01_methane but with the one with 05_polyethilene-co-styrene if it works, I am just learning the source code which is worth to bother.

**Comment by jcminerlanl** [comment]
I ran into the same problem with the 01_methane 'dreiding' example.

The 'gaff2' example produces a different problem:
```
starting fire_min LAMMPS simulation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jcminer/pysimm/pysimm/lmps.py", line 1122, in quick_min
    sim.run(np, nanohub)
  File "/home/jcminer/pysimm/pysimm/lmps.py", line 956, in run
    call_lammps(self, np, nanohub, prefix=prefix)
  File "/home/jcminer/pysimm/pysimm/lmps.py", line 1019, in call_lammps
    stdin=PIPE, stdout=PIPE, stderr=PIPE)
  File "/home/jcminer/anaconda3/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/jcminer/anaconda3/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/home/jcminer/anaconda3/envs/my-rdkit-env/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This came from running:
```
>>> s = system.System()
>>> m = s.molecules.add(system.Molecule())
>>> f = forcefield.Gaff2()
>>> s.forcefield = f.name
>>> gaff_c3 = s.particle_types.add(f.particle_types.get('c3')[0].copy())
>>> gaff_hc = s.particle_types.add(f.particle_types.get('hc')[0].copy())
>>> c1 = s.particles.add(system.Particle(type=gaff_c3, x=0, y=0, z=0, charge=0, molecule=m))
>>> h1 = s.add_particle_bonded_to(system.Particle(type=gaff_hc, charge=0, molecule=m), c1, f)
>>> h2 = s.add_particle_bonded_to(system.Particle(type=gaff_hc, charge=0, molecule=m), c1, f)
>>> h3 = s.add_particle_bonded_to(system.Particle(type=gaff_hc, charge=0, molecule=m), c1, f)
>>> h4 = s.add_particle_bonded_to(system.Particle(type=gaff_hc, charge=0, molecule=m), c1, f)
>>> s.apply_charges(f, charges='gasteiger')
adding gasteiger charges
charges converged after 15 iterations
>>> s.set_box(padding=10)
>>> s.pair_style='lj'
>>> s.bond_style='harmonic'
>>> s.angle_style='harmonic'
>>> lmps.quick_min(s, min_style='fire', name='fire_min', etol=1e-10, ftol=1e-10)
```

My python version is Python 3.6.10 :: (loaded by) Anaconda.

The LAMMPS version came through git and was 'pulled' to the newest version:
 f5a31fefdc45809128368d86f0b4d0503e309330

The version of pysimm was cloned today and has the git version number:
d404a4d6afbd8d8264ddd4273f9206b4b6d8b84a


Any ideas on what the problem could be?

**Comment by AlleksD** [comment]
Hi, 

it seems like a different error to me that is related more to the lammps binary (the way you can/cannot call it on your working computer).

Are there any workload managers (like SLURM  or PBS) that necessary should be used to run your MPI jobs? (can you call mpiexec explicitly?). Also please, check that PySIMM sees LAMMPS: environmental variable LAMMPS_EXEC is defined. 
For another simple check  try to provide explicitly number of processes to the quick_min (the **np** option):

```Python
lmps.quick_min(s, np=1, min_style='fire', name='fire_min', etol=1e-10, ftol=1e-10)
```

If you have any additional logs that are left in the working folder please share it here, it will definitely help to figure out the problem.

Thank you!
Alex

**Comment by jcminerlanl** [comment]
Strangest thing:
When did `cat create.py` and then manually copied the definition into the Python interface and ran that way the code seems to have gone just fine.

I was copying lines individually before that and did not both to create a `def()` to `run()`, so I am not sure what was different, but I guess the problem is resolved.
