### ISSUE TITLE
Problem Calling LAMMPS with Mpiexec

### ISSUE THREAD

**Issue by yaoxiaokun** [polysimtools/pysimm#34]
Hi,
 I am new in Pysimm and tried to run some examples recently. When I run the example 2_Methanol script, the Dreiding force field example run successful, but the Gaff2 return below error. Could anyone give me any suggestion about this? This situation also occur in example 8. Thank you very much!

Traceback (most recent call last):
  File "/home/kun/Desktop/Support/pysimm/Examples/02_methanol/gaff2/create.py", line 24, in <module>
    run()
  File "/home/kun/Desktop/Support/pysimm/Examples/02_methanol/gaff2/create.py", line 15, in run
    lmps.quick_min(s,min_style='fire',settings={'np':1})
  File "/home/kun/pysimm/pysimm/lmps.py", line 1121, in quick_min
    sim.run(np, nanohub)
  File "/home/kun/pysimm/pysimm/lmps.py", line 957, in run
    raise PysimmError('There was a problem calling LAMMPS with {}'.format(prefix))

**Comment by yaoxiaokun** [comment]
pysimm.utils.PysimmError:There was a problem calling LAMMPS with mpiexec.

**Comment by zidan0x266** [comment]
Hi Xiaokun, I think the problem is that pysimm cannot find Lammps excutable.

As mentioned in the tutorial, you have to add lammps path to your environmental file:
`echo "export LAMMPS_EXEC=/usr/bin/lmp_mpi" >> ~/.bashrc`
After that you can check whether it is succeed:
`from pysimm import lmps`
`lmps.check_lmps_exec()`

**Comment by yaoxiaokun** [comment]
Thank you for your reply! I had double checked my bashrc and confirmed I had set the correct path as below.
<img width="1158" alt="截屏2022-10-18 14 45 12" src="https://user-images.githubusercontent.com/114919940/196548417-1338b9d1-0004-4e13-859b-af3a11ef5739.png">
And the dreiding force field still can run successfully. That's why I really confused.

**Comment by yaoxiaokun** [comment]
Thank you for your reply! I had double checked the bashrc and confirmed that the path is correct as below figure.
![截屏2022-10-18 22 27 18](https://user-images.githubusercontent.com/114919940/196548773-6bd2f132-fa94-4402-8381-d1502d9a1ea9.png)
The Drieding force field still could run successfully, that's why I am really confused.

**Comment by zidan0x266** [comment]
It works for me, please check your lammps installation.
`from pysimm import lmps`
`lmps.check_lmps_exec()`
The above commands should return "True".
<img width="1024" alt="Snipaste_2022-10-18_16-51-25" src="https://user-images.githubusercontent.com/17472034/196551886-f43ec93f-50f3-4550-9e60-788589f04cc5.png">

**Comment by yaoxiaokun** [comment]
Thank you for your reply again!
I also return a 'True', But the example fail
![截屏2022-10-18 23 59 00](https://user-images.githubusercontent.com/114919940/196560722-77906561-ea05-4c1e-8a40-7c462f67f61d.png)

**Comment by zidan0x266** [comment]
Hi Xiaokun,

I have tried both on my laptop and on the cluster, all work well as it should. To better solve the problem, can you describe step by step your installation procedure?

Further, depend on your error message, can you add `prefix = "mpirun -np 8"` to your create.py?

`def run(test=False, prefix="mpirun -np 8"):`

Please be noted that this "prefix" is user dependent, it relies on your mpi environment, for instance, on my cluster, it will be prefix = "ibrun -np 8". Hope this could help!

**Comment by yaoxiaokun** [comment]
Dear Zidan,
Thanks for your sincere help.  I followed the complete installation (pysimm and lammps) suggestion in README.md to install. Therefore,  maybe there are some softwares I have not download? 
<img width="861" alt="截屏2022-10-19 10 57 58" src="https://user-images.githubusercontent.com/114919940/196660185-b0211424-e9ce-4fde-b5ad-ecdfb05c8a3b.png">

In addition, I had tried to add the message prefix="mpirun -np 2" to my create.py. but it dosen't work.

**Comment by yaoxiaokun** [comment]
Dear Zidan,
I found out how to solve my situation now. The latest release LAMMPS have not contain the user-misc package which is important for gaff2 forcefield. The auto download haven't mention the missing of user-misc package. Hence, I changed my LAMMPS to before version (2021) and it work.
Thank you again for your help!
